# Site settings
title: Victor Crespo-Rodriguez
domain: victorcrespo.xyz
url: "https://victorcrespo.xyz"
baseurl: "/"
# url: "https://kssim.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Victor Crespo-Rodriguez
  desc: My personal website
  email: me@victorcrespo.xyz
  selfie: assets/img/profile.png

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: crespovictor
  bluesky: victorcrespo.xyz
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/crespovictor/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"
  google_scholar: True

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/publications/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
